#!/usr/bin/env sh

#
# Gradle start up script for POSIX generated by Gradle.
#
# SPDX-License-Identifier: Apache-2.0
#

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
  APP_HOME=${app_path%/*}
  [ -h "$app_path" ]
do
  ls=$(ls -ld "$app_path")
  link=${ls#*-> }
  case $link in
    /*) app_path=$link ;;
    *) app_path=$APP_HOME/$link ;;
  esac
 done

APP_HOME=$(cd "${APP_HOME:-./}" && pwd -P) || exit

APP_NAME="Gradle"
APP_BASE_NAME=${0##*/}

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='-Xmx64m -Xms64m'

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
  echo "${APP_BASE_NAME}: $*"
}

die () {
  echo
  echo "${APP_BASE_NAME}: $*"
  echo
  exit 1
}

# OS specific support functions.
case "$(uname)" in
  CYGWIN*|MINGW*|MSYS*)
    unix=true
    ;;
  Darwin*)
    darwin=true
    ;;
  *)
    ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
  if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
    # IBM's JDK on AIX uses strange locations for the executables
    JAVACMD=$JAVA_HOME/jre/sh/java
  else
    JAVACMD=$JAVA_HOME/bin/java
  fi
  if [ ! -x "$JAVACMD" ] ; then
    die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME"
  fi
else
  JAVACMD=java
fi

if ! command -v "$JAVACMD" >/dev/null 2>&1; then
  die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH."
fi

# Increase the maximum file descriptors if we can.
if [ "$MAX_FD" != "maximum" ] ; then
  ulimit -n "$MAX_FD" >/dev/null 2>&1 || warn "Could not set maximum file descriptor limit"
fi

# For Darwin, add options to specify how the application appears in the dock
if [ "$darwin" = "true" ] ; then
  GRADLE_OPTS="$GRADLE_OPTS -Xdock:name=$APP_NAME"
fi

# For Cygwin or MSYS, switch to Windows paths for the jar file.
if [ "$unix" = "true" ] ; then
  CLASSPATH=$(cygpath --path --mixed "$CLASSPATH")
  JAVACMD=$(cygpath --unix "$JAVACMD")
  APP_HOME=$(cygpath --unix "$APP_HOME")
fi

exec "$JAVACMD" $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
